#!/bin/bash

# Builder details
export VM_IP="128.219.187.233"
export CONTROL_SOCKET='~/.ssh/ControlSocket-%l%h%p%r'
export KEY_FILE="${HOME}/.ssh/BuilderKey"
KEY_FILE_GLOBAL='./BuilderKey'

if [ $# -ne 2 ]; then
  echo "Usage: builder container.name container.def"
  exit 1
fi

NAME_PATH="$1"
DEF_PATH="$2"

# Create /.ssh directory if it doesn't exist
mkdir -p ${HOME}/.ssh
chmod 700 ${HOME}/.ssh

# Copy builder key and set correct permissions
cp ${KEY_FILE_GLOBAL} ${KEY_FILE}
chmod 600 ${KEY_FILE}

# On exit kill control master process
# Not all shells call EXIT on SIGHUP/INT/TERM so we trap them
# Once we've trapped once ignore further abnormal traps(hitting ctrl-c a bunch)
function null_cleanup {
  trap null_cleanup HUP INT TERM PIPE QUIT ABRT
}
function cleanup {
  trap null_cleanup HUP INT TERM PIPE QUIT ABRT
  /usr/bin/ssh -S${CONTROL_SOCKET} -F/dev/null -i${KEY_FILE} -oStrictHostKeyChecking=no builder@${VM_IP} 'BuilderCleanup'
  /usr/bin/ssh -O exit -S${CONTROL_SOCKET} -t -F /dev/null -i${KEY_FILE} -oStrictHostKeyChecking=no builder@${VM_IP}
  exit
}
trap cleanup HUP INT TERM PIPE QUIT ABRT ERR

# Setup a control master socket so that all commands utilize the same connection
# This allows us to ensure that all subsuquent operations originate from the same user/session
# https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing
/usr/bin/ssh -f -N -M -S${CONTROL_SOCKET} -F/dev/null -i${KEY_FILE} -oStrictHostKeyChecking=no builder@${VM_IP}

# Prepare the builder for building
/usr/bin/ssh -S${CONTROL_SOCKET} -F/dev/null -i${KEY_FILE} -oStrictHostKeyChecking=no builder@${VM_IP} 'BuilderPrep'

# Copy definition file to builder
/usr/bin/scp -oControlPath=${CONTROL_SOCKET} -F /dev/null -i${KEY_FILE} -oStrictHostKeyChecking=no ${DEF_PATH} builder@${VM_IP}:container.def

# Run the build process
/usr/bin/ssh -S${CONTROL_SOCKET} -F/dev/null -i${KEY_FILE} -oStrictHostKeyChecking=no builder@${VM_IP} 'BuilderRun'

# Copy container file back from builder
/usr/bin/scp -oControlPath=${CONTROL_SOCKET} -F/dev/null -i${KEY_FILE} -oStrictHostKeyChecking=no builder@${VM_IP}:container.img ${NAME_PATH}

# Cleanup the builder
/usr/bin/ssh -S${CONTROL_SOCKET} -F/dev/null -i${KEY_FILE} -oStrictHostKeyChecking=no builder@${VM_IP} 'BuilderCleanup'

cleanup
