#!/bin/bash

# Get script directory
SCRIPT_DIR=$(dirname $0)

# OpenStack credentials
if [ "$1" != "--no_source" ]; then
  source ${SCRIPT_DIR}/openrc.sh
fi

# Remove Key
nova keypair-delete CadesKey
rm ${SCRIPT_DIR}/CadesKey
rm ${SCRIPT_DIR}/BuilderKey

# Remove IP file
rm ${SCRIPT_DIR}/BuilderIP

# Delete VM
nova delete ContainerBuilder
